basePath: /
definitions:
  models.Product:
    properties:
      name:
        example: Great product
        type: string
      price:
        example: 20
        type: number
      stock:
        example: 10
        type: integer
    type: object
info:
  contact:
    name: Onat
  description: This is a simple API for Products
  license:
    name: MIT
    url: https://mit-license.org/
  title: Products App
  version: "1.0"
paths:
  /api/product:
    post:
      consumes:
      - application/json
      description: Add a new product
      parameters:
      - description: Register product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Add a new product
      tags:
      - Products
  /api/product/{id}:
    delete:
      consumes:
      - application/json
      description: Remove product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "503":
          description: Service Unavailable
          schema:
            type: string
      summary: Remove product by ID
      tags:
      - Products
    get:
      consumes:
      - application/json
      description: Get product by ID
      parameters:
      - description: GetSingleProduct ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "404":
          description: Not Found
          schema:
            type: string
        "503":
          description: Service Unavailable
          schema:
            type: string
      summary: Get product by ID
      tags:
      - Products
    put:
      consumes:
      - application/json
      description: UpdateProduct product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: UpdateProduct product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "503":
          description: Service Unavailable
          schema:
            type: string
      summary: UpdateProduct product by ID
      tags:
      - Products
  /api/products:
    get:
      consumes:
      - application/json
      description: Get all products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
        "503":
          description: Service Unavailable
          schema:
            type: string
      summary: Get all products
      tags:
      - Products
swagger: "2.0"
